GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/63fe17c66a2c935aad6562f0

###

DELETE http://localhost:3001/api/persons/5

###

POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "ew",
    "number": "040-123456"
}

###

GET http://localhost:3001/api/sos/3

###